baseurl = "https://mc.sciroccogti.top/"
languageCode = "zh-cn"
title = "暗夜基地"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "暗夜基地MC服务器"
	description = "a mc server for Dark Night Base"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "暗夜基地"

		[params.navigation.links]
			about     = "About"
			services  = "Map"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "暗夜基地"
		subtitle   = "a pure survival Minecraft server for Dark Night Base"
		buttonText = "查看地图"
		link       = "https://mc.sciroccogti.top/map/"


	# About section
	[params.about]
		headline    = "关于本服"
		description = "这是一个由一群学生建立的 Minecraft 纯净生存服，在生存模式下打造自己的多彩世界"
		buttonText  = ""
		

	# Service section
	[params.services]
		headline = ""

        [[params.services.list]]
		icon = "fa-github"
		title = "GitHub"
		description = "我们为 MCDReforged、MCDaemon-go 贡献插件，并积极开发新款 MCD"

        [[params.services.list]]
		icon = "fa-balance-scale"
		title = "Pure Survival Server"
		description = "纯净生存，原汁原味"

	[[params.services.list]]
		icon = "fa-wrench"
		title = "Redstone Machines"
		description = "我们学习、建造高效稳定的生电设施"

        [[params.services.list]]
		icon = "fa-gamepad"
		title = "Play with Love"
		description = "热爱，快乐，这是我们的终极主题"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Builder"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	#[params.aside]
	#	headline = "了解更多细节"

	#	[params.aside.button]
	#		text = "查看指南"
	#		link = "//www.sciroccogti.top/mc"

	# Contact section
	[params.contact]
		headline = "了解更多"
		description = ""
	#	phone = "123-456-6789"
		email = "scirocco_gti@yeah.net"
		github = "https://github.com/Dark-Night-Base"
		githubname = "Dark-Night-Base"
		map = "https://mc.sciroccogti.top/map/"
		mapname = "BlueMap"
	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
